language: rust
rust:
  - 1.44.1  # minimum supported toolchain; used for clippy/rustfmt as well
  - stable
  - beta
  - nightly

arch:
  - amd64
  - s390x

matrix:
  allow_failures:
    - rust: nightly
    # VM apparently has broken network access
    - rust: 1.41.0
      arch: s390x

env:
  global:
    - MSRV=1.44.1

before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$MSRV" ]]; then
      rustup component add clippy rustfmt;
    fi'

script:
  - cargo test
  - cargo test --features rdcore
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$MSRV" ]]; then
      cargo clippy -- -D warnings;
      cargo clippy --features rdcore -- -D warnings;
      cargo fmt -- --check;
    fi'
