[package]
name = "coreos-installer"
repository = "https://github.com/coreos/coreos-installer"
license = "Apache-2.0"
edition = "2018"
exclude = ["/.github", "/.gitignore", "/.travis.yml", "/Dockerfile"]
authors = [ "Benjamin Gilbert <bgilbert@redhat.com>" ]
description = "Installer for Fedora CoreOS and RHEL CoreOS"
version = "0.1.3-alpha.0"

[package.metadata.release]
sign-commit = true
disable-push = true
disable-publish = true
pre-release-commit-message = "cargo: coreos-installer release {{version}}"
post-release-commit-message = "cargo: development version bump"
tag-message = "coreos-installer v{{version}}"

[[bin]]
name = "coreos-installer"
path = "src/main.rs"

[profile.release]
lto = true

[dependencies]
clap = "2.33"
cpio = "0.2.0"
byte-unit = "^3.0.3"
error-chain = { version = "0.12", default-features = false }
flate2 = "^1.0.13"
nix = "^0.17.0"
progress-streams = "^1.1.0"
regex = "1.3.4"
reqwest = { version = "^0.10.3", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.1.0"
url = "^2.1.1"
xz2 = "^0.1.6"

[dev-dependencies]
maplit = "1.0"
