---
name: Rust
on:
  push:
#    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  # Minimum and linting toolchain
  ACTIONS_PINNED_TOOLCHAIN: 1.44.1

jobs:
  tests-stable:
    name: "Tests, stable toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          default: true
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
      - name: cargo build (rdcore)
        run: cargo build --features rdcore
      - name: cargo test (rdcore)
        run: cargo test --features rdcore
  lints:
    name: "Lints, pinned toolchain"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env['ACTIONS_PINNED_TOOLCHAIN']  }}
          default: true
          components: rustfmt, clippy
      - name: cargo fmt (check)
        run: cargo fmt -- --check -l
      - name: cargo clippy (warnings)
        run: cargo clippy -- -D warnings
      - name: cargo clippy (rdcore, warnings)
        run: cargo clippy --features rdcore -- -D warnings
  tests-other-channels:
    name: "Tests, unstable toolchain"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        channel:
          - "beta"
          - "nightly"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.channel }}
          default: true
      - name: cargo build
        run: cargo build
      - name: cargo test
        run: cargo test
      - name: cargo build (rdcore)
        run: cargo build --features rdcore
      - name: cargo test (rdcore)
        run: cargo test --features rdcore
